# background threshold
bg_thres: 300
# resolution level
level: 2
# channel number, 0 means 488
channel: 0
# cube size accepted by the segmentation model
chunk_size: 300
# thickness of one brain slice
splice: 100

# ROI you wanna segment, 'null' means the entire volume to be processed
# format: [x_start, y_start, z_start, x_size, y_size, z_size]
# roi: [0,0,0,128,128,128]
roi: null

# where your image data
# input_path: 'test/data/test.tif'
# input_path: '/share/home/liuy/project/data/VISoR_Unorganized/data/2-50w-ROI.ims'
# input_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20241127_CYT_BCP_T093-F005_VGAL4-1E9_1/ROI_488_2_T093.ims'
# input_path: '/share/data/VISoR_Reconstruction/TestData/20241014_QXY_40X20X_T060C-1_2_1/export-volume.ims'
input_path: '/home/ryuuyou/mnt/VISoR_Reconstruction/TestData/20241014_QXY_40X20X_T060C-1_2_1/export-volume.ims'

# where the database file is output'
# output_path: 'test/out/test.db'
# output_path: 'test/out/2-50w-ROI.db'
# output_path: 'test/out/ROI_488_2_T093.db'
output_path: 'test/out/t060c_7slice.db'
