# background threshold
bg_thres: 150
# resolution level
level: 0
# channel number, 0 means 488
channel: 0
# cube size accepted by the segmentation model
patch_size: 300
# thickness of one brain slice
slice_thickness: 300

# ROI you wanna segment, 'null' means the entire volume to be processed
# format: [x_start, y_start, z_start, x_size, y_size, z_size]
# roi: [0,0,0,128,128,128]
roi: null

# whether to keep branch in segmentation output
# if true, the edges of the branches will be kept in the segmentation result
# if false, the branches will be removed from the segmentation result
keep_branch: false

ckpt_path: '/share/home/liuy/project/SegFiber_dev/out/weights/for_C534/best_val_model_tiny.pth'
# # where your image data
# input_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250604_SJZ_SEED_PD-5E8_C534_1/Recon_4um_optimize/Recon_1um_optimize/C534_1um.ims'
# input_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250504_YY_SEED_TVR-5E7-24_8954_1/Reconstruction_1um/ROIImage/1.0.ims'
# input_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250418_YY_BCP_CAMKII_T154_1/T154_1um.ims'
input_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250612_YY_CAMKII_1E9-59D_T155_1/Reconstruction_1um/ROIImage/1.0.ims'
# # to sqlite file
# output_path: '/share/home/liuy/project/data/neurofly_data/db/SEED_C534_1um_SegFineTune.db'
# output_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250418_YY_BCP_CAMKII_T154_1/SEED_T154_1um.db'
output_path: '/share/data/VISoR_Reconstruction/SIAT_SIAT/XuFang/Mouse_Brain/20250612_YY_CAMKII_1E9-59D_T155_1/Reconstruction_1um/ROIImage/SEED_T155_1um.db'

# workstation test
# input_path: 'test/neurofly_data/img/test.tif'
# output_path: 'test/neurofly_data/db/test.db'